### PR TITLE
Adds netstandard2.0 as target framework. 

### PR DESCRIPTION
**Pull request by ChrSteinert**
Additionally excludes some NuGets that are not necessary anymore for `net461` and `netstandard2.0`.

### CODE REVIEW

**Comment by ChrSteinert** [comment]
Ok - so it builds. But a test fails.
Don't think my change introduced that...

**Comment by jackmott** [comment]
Investigating, its probably just an unlucky delta on SIMD summation differing.

**Comment by jackmott** [comment]
one package refers to system.numerics.vectors 4.3 and another 4.4, is that on purpose?

**Comment by ChrSteinert** [comment]
Nope, did I miss some reference?
Will look again!

**Comment by ChrSteinert** [comment]
Cool. For whatever reason the test now succeeds 😄 

I saw that the package incompat is in bechmarks file. Will fix that.
Should I revert the Tests.csproj file?

**Comment by jackmott** [comment]
floating point addition is neither commutative nor associative so when you sum up with SIMD the result differs, the test uses a delta but I guess we got unlucky! 

revert the tests.csproj file?

**Comment by jackmott** [comment]
want to change that failing test to have a 0.15 tolerance instead of 0.1?

**Comment by ChrSteinert** [comment]
I changed the Tests.csproj. Without actuall need it seems. 
Should I revert this commit: https://github.com/jackmott/LinqFaster/pull/10/commits/878be62346f7d12834de1e4b060c0d43c6ac97c6 ?

**Comment by jackmott** [comment]
sure

**Comment by jackmott** [comment]
ok LGTM you ready to merge?

**Comment by ChrSteinert** [comment]
Cool! 😄

Sure. I guess you can do new version numbers on your own! 😁

**Comment by ChrSteinert** [comment]
Can you give some timeline on when netstandard2.0 will be on NuGet. Want to use it in https://github.com/ChrSteinert/FSPerfTests ;)

**Comment by jackmott** [comment]
I'll try to get it done over the weekend.

**Pull request merged**
